services:
    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes:
            - ./server/src/:/app/server/src/

    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db

    client:
        build: ./client
        ports:
            - 3030:3000
        command: npm start
        volumes:
            - ./client/src/:/app/src/
            - ./client/public/:/app/public/
        depends_on:
            - server
